### ISSUE TITLE
Option to silence warnings

### ISSUE THREAD

**Issue by michaelhays** [thetarby/django-auto-related#2]
Hi, thanks for the great library. [This warning](https://github.com/thetarby/django-auto-related/blob/34755a9d3278998d1ad50ce96edfe57437069896/auto_related/tracer.py#L99) is thrown in a few places for a project I'm working on, particularly when there is a field on a serializer that doesn't correspond to a model field. Is there a way to silence this warning?

**Comment by michaelhays** [comment]
Found a workaround for now, suggested [here](https://stackoverflow.com/a/3920894/3414529):

```py
import warnings


class ParentList(generics.ListAPIView):
    serializer_class = SomeSerializer

    def get_queryset(self):
        tracer = Tracer(self.get_serializer())
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            traces = tracer.trace()
        select_related, prefetch_related = optimized_queryset_given_trails(traces)
        ...
```

Still, a configurable option to silence these would be nice.

**Comment by thetarby** [comment]
Hi, thanks for the feedback I think it will be better to use logging library instead of printing warning, what do you think? I am not sure if this should be a info level or warning level log but either way you should be able to silence all logs from auto-related with one line of code if I use logging. I will update it very soon.

**Comment by michaelhays** [comment]
Yes good idea. Sounds like you know what to do, but [here](https://github.com/GeeWee/django-auto-prefetching/blob/ee9a554a1b87a6f4713126c157a986f9aafe1b89/django_auto_prefetching/__init__.py#L18) is an example of how a similar library does that, if that helps.

**Comment by michaelhays** [comment]
I made a small repo to demonstrate the problem: https://github.com/michaelhays/auto_related_warnings

Running the [tests](https://github.com/michaelhays/auto_related_warnings/blob/main/auto_related_warnings/users/tests.py) outputs the following warning for `test_retrieve_user`:

```
UserWarning: auto-related: Source cannot be traced: ['some_serializer_field']. Hence it might not be fully optimized.
```

The important part is in [serializers.py](https://github.com/michaelhays/auto_related_warnings/blob/main/auto_related_warnings/users/serializers.py):

```py
class UserSerializer(serializers.ModelSerializer):
    password = serializers.CharField(write_only=True)
    some_serializer_field = serializers.CharField(write_only=True)

    class Meta:
        model = User
        fields = [
            "id",
            "email",
            "password",
            "some_serializer_field",
            "some_model_field",
        ]
        read_only_fields = [
            "some_model_field",
        ]

    def create(self, validated_data):
        some_serializer_field = validated_data.pop("some_serializer_field")

        return User.objects.create(
            **validated_data,
            some_model_field=f"(Model) {some_serializer_field}",
        )
```

`django-auto-related` throws the error because `some_serializer_field` isn't a field on the `User` model. Maybe `write_only` fields should be excluded from this warning?

**Comment by thetarby** [comment]
Thanks for your help I have updated to use logging instead of warnings. Now that warning is an info level log so normally it will not be logged unless you explicitly set log level to display info level logs. With version 0.0.4 you dont have to do anything but still if you want to silence all logs from auto-related you can do;

```python
# this goes to somewhere in your project
logging.getLogger('django-auto-related').propagate = False
```

Also you can check out [logging docs](https://docs.python.org/3/library/logging.html) to see how to set log level to lower or higher or how to customize logging in your project generally.

**Comment by michaelhays** [comment]
Working great, appreciate the help!
